# all: presentacion.tex
# 	pdflatex -shell-escape presentacion.tex && bibtex presentacion.aux && pdflatex -shell-escape presentacion.tex && pdflatex -shell-escape presentacion.tex
all: presentacion.tex
	pdflatex presentacion.tex
